name: Publish new release to crates.io
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish-to-cargo:
    name: cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-to-ghcr:
    name: docker publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Get package version
        id: get_version
        run: echo "VERSION=$(grep '^version' Cargo.toml | head -n 1 | cut -d '"' -f 2)" >> "$GITHUB_OUTPUT"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/flother/spreet:latest -t ghcr.io/flother/spreet:${{ steps.get_version.outputs.VERSION }}
      - name: Push Docker image
        run: |
          docker push ghcr.io/flother/spreet:latest
          docker push ghcr.io/flother/spreet:${{ steps.get_version.outputs.VERSION }}
